# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10367532dae62ac3620a8a5082eb3a75b0907a30fcf704cdf73694ab8f11bbda62d8e0971122173f9b94d25463ea260ac2cf1bf42f16aa3d507efbf77586e5a8

test:
  secret_key_base: 89293e57d525b1d264b82881eb0dd234ceb1e16ad737db631e5245000df6eb9f1e5106994e6af8185bf29cdcf0902d19b86ee1ac439be9441607ced844024d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
