# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|


  ######################################
  ######Useful configs #################
  ######################################
  #config.vm.box       = ""
  #config.vm.box_url   = ""
  #config.ssh.username = ""
  ####### End Useful configs ############

  config.vm.box = "amickglass"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "src/", "/home/vagrant/src"
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.

end
